### ISSUE TITLE
Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"

### ISSUE THREAD

**Issue by lostcodingsomewhere** [nodkz/mongodb-memory-server#772] opened 2023-06-22 20:02 UTC
## Versions

- NodeJS: 18
- mongodb-memory-server-*: 8.13.0
- mongodb(the binary version): 0.0.0
- mongoose: 7.3.1
- system: 

package: mongo-memory-server

## What is the Problem?

Docker (github actions) running into error when starting up the server for tests -- specifically "libcrypto.so.1.1".

Only became an issue this week. No issue when running outside of docker. Have tried to downgrade versions

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
test_1        |  StdoutInstanceError: Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"
test_1        |     at MongoInstance.checkErrorInLine (/app/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:678:11)
test_1        |     at MongoInstance.stderrHandler (/app/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:563:10)
test_1        |     at Socket.emit (node:events:513:28)
test_1        |     at Socket.emit (node:domain:489:12)
test_1        |     at addChunk (node:internal/streams/readable:324:12)
test_1        |     at readableAddChunk (node:internal/streams/readable:297:9)
test_1        |     at Socket.Readable.push (node:internal/streams/readable:234:10)
test_1        |     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

</details>

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2023-06-22 20:12
from what i can tell, this issue is a duplicate of #732

i dont know why it started happening this week, but the TL;DR is that ubuntu 22.04 (ex `ubuntu:latest`) does not ship libraries for `libcrypto 1.1` anymore and [the default binaries are currently 5.0.x](https://nodkz.github.io/mongodb-memory-server/docs/guides/mongodb-server-versions#mongodb-memory-server-core-version-table), which dont have a native version for ubuntu 22.04, only 6.0.4 or higher have builds for this ubuntu version

see [config option `VERSION`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version) on how to configure a binary version

**Comment by lostcodingsomewhere** [comment] 2023-06-22 20:24
thanks @hasezoey -- switching to node:lts-bullseye worked, as suggested by @sagrawal31

**Closed** 2023-06-22 20:24 UTC
Labels: bug, duplicate
