### ISSUE TITLE
Intermittent "Unable to acquire lock" error using replica sets

### ISSUE THREAD

**Issue by MarkPolivchuk** [nodkz/mongodb-memory-server#210] opened 2019-08-01 22:00 UTC
When I make the first write with transactions using replicaSets, I intermittently get the following error. This occurs on the #208 branch as well as 5.1.9. Subsequent writes work as expected.

```ts
import { MongoMemoryReplSet } = from 'mongodb-memory-server-global';

mongod = new MongoMemoryReplSet({
    replSet: {
        name: 'rsTest',
        auth: false,
        args: [],
        count: 1,
        dbName: 'test',
        ip: '0.0.0.0',
        oplogSize: 1,
        spawn: {},
        storageEngine: 'wiredTiger'
    },
    binary: {
        debug: config.MONGOOSE_DEBUG as boolean,
        version: (config.MONGO_VERSION as string) || 'latest'
    },
    debug: config.MONGOOSE_DEBUG as boolean
});

await mongod.waitUntilRunning();

const mongoConnectionString = `${await mongod.getConnectionString()}?replicaSet=rsTest`;

const instance = await mongoose.connect(mongoConnectionString, mongooseOptions);

return instance;
```

```
MongoError: Unable to acquire lock \'{6989642780905297871: Database, 72113753264216015}\' within a max lock request timeout of \'5ms\' milliseconds.
    at Connection.<anonymous> (/Users/markpolivchuk/Code/NeoFinancial/bank-monorepo/node_modules/mongodb-core/lib/connection/pool.js:443:61)
    at Connection.emit (events.js:189:13)
    at Connection.EventEmitter.emit (domain.js:441:20)
    at processMessage (/Users/markpolivchuk/Code/NeoFinancial/bank-monorepo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/Users/markpolivchuk/Code/NeoFinancial/bank-monorepo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by jardakotesovec** [comment] 2019-08-02 19:50
@MarkPolivchuk If you put there some additional wait before the first write, does that resolve the problem? Just double checking with you if thats another timing related issue and we don't wait long enough inside `waitUntilRunning()`

**Comment by jardakotesovec** [comment] 2019-08-02 19:53
@MarkPolivchuk Can you provide complete example to reproduce?

**Comment by MarkPolivchuk** [comment] 2019-08-08 21:04
I'm having trouble replicating outside of our internal project, but I can confirm that it's still issue on `5.1.10`. I'll try to get you a working example. 

Prior to 5.10, I needed a `wait(2000)` between `waitUntilRunning()` and `mongoose.connect(...)` as well as one after `mongoose.connect(...)`. 

Now it looks like the one after `waitUntilRunning()` is no longer needed. Increasing the timeout after `mongoose.connect()` but before write reduces the frequency of the `Unable to acquire lock` error I'm seeing.

**Comment by MarkPolivchuk** [comment] 2019-08-09 19:19
Still having trouble reproducing in a fresh project. I've worked around this in our internal project by polling writes until one succeeds, after which all subsequent writes succeed. 

```
const testConnection = async (db: mongoose.Mongoose, attempts = 10): Promise<void> => {
  if (attempts === 0) {
    throw new Error('Unable to write to replica set database within timeout');
  }

  try {
    await db.connection.createCollection('testCollection');

    const session = await db.startSession();

    await session.startTransaction();
    await db.connection.collection('testCollection').insertOne({ time: new Date() }, { session });
    await session.commitTransaction();
    await session.endSession();

    return Promise.resolve();
  } catch (error) {
    logger.error(error);

    await delay(500);

    return testConnection(db, attempts - 1);
  }
};

const connect = async (): Promise<mongoose.Mongoose> => {
  const mongod = new MongoMemoryReplSet();
  await mongod.waitUntilRunning();
  const mongoConnectionString = `${await mongod.getConnectionString()}?replicaSet=rsTest`;

  const db = await mongoose.connect(mongoConnectionString, mongooseOptions)

  await testConnection(db);

  return db;
};
```

**Comment by jardakotesovec** [comment] 2019-08-11 17:37
Hi, @MarkPolivchuk - you probably seen [this](https://stackoverflow.com/questions/54327147/mongoerror-unable-to-acquire-lock) issue on SO. 

Maybe you could try that `maxTransactionLockRequestTimeoutMillis` command.. as suggested there. If that would solve the problem, you could propose to calling this command inside mongodb-memory-server so it works by default.

**Comment by hasezoey** [comment] 2019-12-27 17:46
is this still an issue in later version of this package?
and which mongodb & node-driver versions were used?

**Comment by hasezoey** [comment] 2020-09-07 06:39
because this seems like an timing related issue, i will close it as duplicate

Duplicate of #166

**Closed by hasezoey** 2020-09-07 06:39 UTC
Labels: Needs More Information
