### ISSUE TITLE
MongoDB downloader supports HTTPS only URLs

### ISSUE THREAD

**Issue by kamarkiewicz** [nodkz/mongodb-memory-server#473] opened 2021-05-11 07:42 UTC
## Versions

- NodeJS: 0.0.0
- mongodb-memory-server-*: 0.0.0
- mongodb: 0.0.0
- system: Any (tested on Windows)

package: mongo-memory-server-core

## What is the Problem?

HTTP links which don't have redirection to HTTPS are failing.

## Code Example

N/A

## Do you know *why* it happens?

util MongoBinaryDownload.ts uses https package directly. Quick code skimming shows the URL is rewritten to be HTTPS.
I'd suggest delegating actual dependency downloading to some package.

**Comment by hasezoey** [comment] 2021-05-11 08:01
Duplicate of #172

**Closed by hasezoey** 2021-05-11 08:01 UTC
Labels: bug
