### ISSUE TITLE
Error downloading mongodb binary version for Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by AhmedY0unes** [nodkz/mongodb-memory-server#722] opened 2022-12-11 10:57 UTC
## Versions

- NodeJS: 16.18.0
- mongodb-memory-server-*: v8.10.1
- mongodb(the binary version): 4.4.9 
- system: Linux ubuntu 22.04.1

package: mongo-memory-server

## What is the Problem?

Error Downloading the binary version of mongodb 4.4.9 on ubuntu 22.04.

## Debug Output
```
Error: Jest: Got error running globalSetup - /home/runner/work/setup.ts, reason: Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
  Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-4.4.9.tgz"
Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
List of available versions can be found here:
  https://www.mongodb.org/dl/linux for Linux
  https://www.mongodb.org/dl/osx for OSX
  https://www.mongodb.org/dl/win32 for Windows
    at ClientRequest.<anonymous> (/home/runner/work/node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:418:17)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:[29](https://github.com/wuilt/wuilt-services/actions/runs/3668510136/jobs/6201696951#step:11:30)0:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
error Command failed with exit code 1.
error Command failed.
Exit code: 1
Command: /opt/hostedtoolcache/node/14.17.6/x64/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js test:coverage
Directory: /home/runner/work
Output:

Error: Process completed with exit code 1.
```

## Do you know *why* it happenes?
When I tried changing the ubuntu version to 20.04, it worked as it should and the mongodb binary version downloaded successfully.

**Comment by hasezoey** [comment] 2022-12-11 13:06
cannot reproduce, could you provide the output of the following?

```sh
$ cat /etc/upstream-release/lsb-release

Output Here

$ cat /etc/os-release

Output Here

$ cat /usr/lib/os-release

Output Here

$ cat /etc/lsb-release

Output Here
```

also any config you may have set for MMS, (package.json `config: { "mongodbMemoryServer": { allInHere } }` and all environment variables starting with `MONGOMS_`, if not set in the command it should be easy as `printenv | grep "MONGOMS_"`)

---

for reference, i did the following to test:

```ts
const du = new MongoBinaryDownloadUrl({
  platform: 'linux',
  arch: 'x64',
  version: '4.4.9',
  os: {
    os: 'linux',
    dist: 'ubuntu',
    release: '2204',
  },
});
utils.assertion(await du.getDownloadUrl() === 'https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.9.tgz')
```

**Comment by JBaczuk** [comment] 2022-12-12 20:42
@hasezoey Is it because the download is cached on your machine? I'm getting the same error. It seems the url for the downloads is no longer accessible.

**Comment by hasezoey** [comment] 2022-12-13 00:39
i will be replying to the original message, because it is easier to explain:

> Is it because the download is cached on your machine?

no, as you can see in the script i had provided, it only *generates the url* and compares it *to what it should be* not downloads or checks the installed binary (`MongoBinaryDownloadUrl` is the url generator and `MongoBinaryDownload` is the downloader which calls `MongoBinaryDownloadUrl` in a normal download process)

> It seems the url for the downloads is no longer accessible.

it was ever accessible in the first place, my point was that i could not get it to generate a `ubuntu2204` link, because all ubuntu versions above `20(04)` (and mongodb version above and equal to 4.4) are mapped to `2004`, because there are no binaries for `2104` or `2204`

relevant code:

https://github.com/nodkz/mongodb-memory-server/blob/9a7abf5aeb4c7aeab014c39193a9cb81bbf1e3be/packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts#L478-L490

---

so i am asking again, could you provide the output from the mentioned files, it will help debug if some the os-information is wrongly interpreted (in my reproduction code i had placed the values as how the *should* have been represented)

<details>
<summary>the files i mean</summary>

```sh
$ cat /etc/upstream-release/lsb-release

Output Here

$ cat /etc/os-release

Output Here

$ cat /usr/lib/os-release

Output Here

$ cat /etc/lsb-release

Output Here
```

</details>

also debug output would be good to have from when the binary is not cached, see [Enable Debug Mode](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode)

**Comment by speedytwenty** [comment] 2022-12-15 21:03
From https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

```
Switch back to Ubuntu 20.04 by specifying the ubuntu-20.04 runner label. We will continue to support Ubuntu 20.04.
```

I'd assume this is a reasonable workaround unless you truly need to test with Ubuntu 22. 

_I get redirected when I visit https://fastdl.mongodb.org/ so it's unclear if there is an image (yet) for Ubuntu 22._

**Comment by hasezoey** [comment] 2022-12-16 14:36
> I get redirected when I visit https://fastdl.mongodb.org/ so it's unclear if there is an image (yet) for Ubuntu 22.

fastdl was never indexable, the old index site got removed and is now at https://www.mongodb.com/download-center/community/releases/archive

---

because no-one did it, here is the output of the `ubuntu:22.04` docker image:

```sh
$ cat /etc/upstream-release/lsb-release

cat: /etc/upstream-release/lsb-release: No such file or directory

$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ cat /usr/lib/os-release

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

which gives the output i would expect and test for, so it outputs the correct url, please provide this data when it somehow does not output the correct url
Note: i have additionally tried installing nodejs in that container and running the mentioned script (while letting automatically infer the os information) and it gives back the url i would expect and mentioned in the fist comment

PS: mongodb-memory-server also uses github-ci to test, and uses `ubuntu-latest` which currently translates to `ubuntu-22.04`

for now i will close this issue because i cannot reproduce it and the required information was not provided

**Closed by hasezoey** 2022-12-16 14:36 UTC
Labels: bug, can't reproduce

**Comment by JBaczuk** [comment] 2023-01-31 00:01
@hasezoey To reproduce try:
```
const du = new MongoBinaryDownloadUrl({
    platform: 'linux',
    arch: 'x64',
    version: '22.04',
    os: {
      os: 'linux',
      dist: 'ubuntu',
      release: '2204',
    },
  });
  expect(await du.getDownloadUrl()).toBe(
    'https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.9.tgz'
  );
```

It looks like the problem is in [https://github.com/nodkz/mongodb-memory-server/blob/0e90784835f4c816e7c9b5bfbb062dc098dd1293/packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts#L415]()

```
getUbuntuVersionString(os: LinuxOS): string {
    let ubuntuOS: LinuxOS | undefined = undefined;
    const coercedVersion = semver.coerce(this.version);
// ...
```

The string '"22.04"` is not valid semver. I guess you can't assume that the `VERSION_ID` stored in these files will be valid semver.

You can get the file contents on github actions like this: https://github.com/JBaczuk/github-actions-demo/actions/runs/4049254110/jobs/6965412983

```
#cat /etc/upstream-release/lsb-release #skipped because missing file
echo "/etc/os-release"
cat /etc/os-release
echo "/usr/lib/os-release"
cat /usr/lib/os-release
echo "/etc/lsb-release"
cat /etc/lsb-release 
  
/etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
/usr/lib/os-release
PRETTY_NAME="Ubuntu [22](https://github.com/JBaczuk/github-actions-demo/actions/runs/4049254110/jobs/6965412983#step:3:23).04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
/etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

**Comment by hasezoey** [comment] 2023-01-31 00:55
@JBaczuk

>       release: '2204',

this is not how it is parsed, maybe just a typo (it would be parsed *with the dot* as `22.04`)

>     version: '22.04',

this is not a valid mongodb version, highest currently existing is `6.0.4` and [the default for MMS 8.11.x is `5.0.13`](https://nodkz.github.io/mongodb-memory-server/docs/guides/mongodb-server-versions#mongodb-memory-server-core-version-table)

> The string "22.04" is not valid semver. I guess you can't assume that the VERSION_ID stored in these files will be valid semver.

this change to semver was after this issue was opened (and closed) in 8.11.2, and `coerce` will try to get a valid semver out of it even if it is not valid as a direct input (example: `22.04` will get coerced to `22.4.0`), which makes comparing ranges way easier

---

i dont see anything wrong with the given output, if you have a issue currently, please open a new issue with all the required information

---

PS: i updated your comment to make it easier to read (adding syntax highlighting and adding spaces between outputs)

**Comment by JBaczuk** [comment] 2023-01-31 19:50
@hasezoey I'm experiencing the same issue as the OP (with a different version of this library), but I think I figured it out.

>   release: '2204',

I just copied this format from your comment above https://github.com/nodkz/mongodb-memory-server/issues/722#issuecomment-1345549923

> this is not a valid mongodb version, highest currently existing is 6.0.4 and [the default for MMS 8.11.x is 5.0.13](https://nodkz.github.io/mongodb-memory-server/docs/guides/mongodb-server-versions#mongodb-memory-server-core-version-table) and in your expected URL it would need to be set to 4.4.9

I misunderstood this field. I thought it was the OS version, being populated from the system release files, but I see this is the MongoDB version.

My `jest-mongodb-config.js` has:

```js
module.exports = {
  mongodbMemoryServerOptions: {
    binary: {
      version: '6.0.3',
      skipMD5: true
    },
    instance: {
      dbName: 'jest'
    },
    autoStart: false
  }
}
```

Also, I was using an older version of `mongodb-memory-server` (`7.6.3`) which may not have had the overrides for versions < `6.0.4` on Ubuntu >= `22.04`. The URL it was generating for me was `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.3.tgz`.

Anyway, I at least have workarounds, feel free to ignore this if you want.

**Comment by hasezoey** [comment] 2023-02-01 02:13
> I just copied this format from your comment above https://github.com/nodkz/mongodb-memory-server/issues/722#issuecomment-1345549923

then i made a typo, sorry

> Also, I was using an older version of mongodb-memory-server (7.6.3)

does upgrading to a newer version fix your issue?

**Comment by JBaczuk** [comment] 2023-06-08 22:43
I downgraded my Github Action runner to Ubuntu 20.04 and it works

**Comment by hasezoey** [comment] 2023-06-09 11:13
>  StdoutInstanceError: Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"

either upgrade to a higher binary version via [`VERSION`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version) (6.0.4 or higher) or install the missing library
