### ISSUE TITLE
Are there plans to upgrade to MongoDB v5?

### ISSUE THREAD

**Issue by juona** [nodkz/mongodb-memory-server#789] opened 2023-08-21 21:23 UTC
The title says it all - I have recently migrated to MongoDB v5 and while this great library still works, I wonder if there will come a day when I use a feature that it doesn't support.

Also, having two versions of MongoDB in the Node modules is less than ideal, not least because MongoDB v4 comes with a ton of unnecessary and weird AWS dependencies.

How difficult would it be to migrate to v5?

**Comment by hasezoey** [comment] 2023-08-22 07:53
Duplicate of #774

**Comment by hasezoey** [comment] 2023-08-22 07:54
TL;DR: duplicate of a issue that was already fixed and is also already released, though only as a beta (`9.0.0-beta.1`)

**Closed by hasezoey** 2023-08-22 07:53 UTC
Labels: question

**Comment by juona** [comment] 2023-08-23 09:17
I see. Apologies for this, I usually do a decent job looking for existing issues, though it looks like this time I did not.
