### ISSUE TITLE
mongod is being installed twice with global

### ISSUE THREAD

**Issue by mdbetancourt** [nodkz/mongodb-memory-server#378] opened 2020-09-15 06:08 UTC
first with mongodb-memory-server and after with mongodb-memory-server-global

**Comment by hasezoey** [comment] 2020-09-15 07:35
i think #174 is related

---

could you please provide what steps you exactly took and what package manager you were using to install it?

**Comment by hasezoey** [comment] 2020-10-12 15:41
Duplicate of #174

**Closed by hasezoey** 2020-10-12 15:41 UTC
Labels: bug
