### ISSUE TITLE
MongoMemoryServer Instance Closes Unexpectedly

### ISSUE THREAD

**Issue by naman114** [nodkz/mongodb-memory-server#755] opened 2023-03-18 11:28 UTC
## Versions

- NodeJS: 16.17.1
- mongodb-memory-server-*: 8.12.1
- mongodb(the binary version): 0.0.0 
- mongodb(the js package): 0.0.0 
- mongoose: 6.5.4 
- system: Linux (Pop!_OS 22.04 LTS) 

package: mongo-memory-server 

## What is the Problem?

Unable to create a MongoMemoryServer Instance

## Code Example

```js
// setupTestDB.js

const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');

let mongo = null;

const connectDB = async () => {
  mongo = await MongoMemoryServer.create();
  const uri = mongo.getUri();
  await mongoose.connect(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
};

const dropDB = async () => {
  if (mongo) {
    await mongoose.connection.dropDatabase();
    await mongoose.connection.close();
    await mongo.stop();
  }
};

const dropCollections = async () => {
  if (mongo) {
    const collections = await mongoose.connection.db.collections();
    for (let collection of collections) {
      await collection.drop();
    }
  }
};

module.exports = { connectDB, dropDB, dropCollections };
```
```js
// __tests__/template.test.js

const { connectDB, dropDB, dropCollections } = require('../setupTestDB');

require('dotenv').config();

beforeAll(async () => {
  try {
    await connectDB();
  } catch (error) {
    console.log(error);
  }
});

afterAll(async () => {
  try {
    await dropDB();
  } catch (error) {
    console.log(error);
  }
});

afterEach(async () => {
  try {
    await dropCollections();
  } catch (error) {
    console.log(error);
  }
});

describe('Example Test Suite', () => {
  test('Example', async () => {
    expect(true).toBe(true);
  });
});
```

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
> cross-env NODE_ENV=test jest --detectOpenHandles

  MongoMS:ResolveConfig Debug Mode Enabled, through Environment Variable +0ms
  MongoMS:ResolveConfig findPackageJson: Found package.json at "/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/package.json" +1ms
  MongoMS:ResolveConfig findPackageJson: Found package with non-empty config field at "/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/package.json" +0ms
  MongoMS:ResolveConfig processConfigOption { debug: '1' } /home/naman114/Projects/Aumyaa/AumRM-Tool/backend +0ms
  MongoMS:MongoMemoryServer create: Called .create() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: start: Called .start() method +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Called MongoMemoryServer._startUpInstance() method +1ms
  MongoMS:MongoMemoryServer Mongo[unknown]: getStartOptions: forceSamePort: false +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance: Creating new MongoDB instance with options: {
  instance: {
    port: 42519,
    dbName: '',
    ip: '127.0.0.1',
    storageEngine: 'ephemeralForTest',
    replSet: undefined,
    dbPath: '/tmp/mongo-mem-2dJgBS',
    tmpDir: '/tmp/mongo-mem-2dJgBS',
    keyfileLocation: undefined,
    launchTimeout: undefined,
    args: undefined,
    auth: false
  },
  binary: undefined,
  spawn: undefined
} +39ms
  MongoMS:MongoInstance create: Called .create() method +0ms
  MongoMS:MongoInstance Mongo[42519]: start +1ms
  MongoMS:MongoBinary getPath +0ms
  MongoMS:DryMongoBinary generateOptions +0ms
  MongoMS:utils tryReleaseFile: "/etc/upstream-release/lsb-release" does not exist +0ms
  MongoMS:getos getLinuxInformation: Using etcOsRelease +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +28ms
  MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '',
  os: {
    os: 'linux',
    dist: 'pop',
    codename: 'jammy',
    release: '22.04',
    id_like: [ 'ubuntu', 'debian' ]
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +1ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13',
  modulesCache: '/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/node_modules/.cache/mongodb-memory-server/mongod-x64-pop-5.0.13',
  relative: '/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/mongodb-binaries/mongod-x64-pop-5.0.13',
  resolveConfig: ''
}  +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Found binary in legacyHomeCache: "/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13" +2ms
  MongoMS:MongoBinary getPath: MongoBinary options: {
  "version": "5.0.13",
  "downloadDir": "/home/naman114/.cache/mongodb-binaries",
  "os": {
    "os": "linux",
    "dist": "pop",
    "codename": "jammy",
    "release": "22.04",
    "id_like": [
      "ubuntu",
      "debian"
    ]
  },
  "platform": "linux",
  "arch": "x64",
  "systemBinary": "",
  "checkMD5": false
} +34ms
  MongoMS:DryMongoBinary locateBinary: Trying to locate Binary for version "5.0.13" +2ms
  MongoMS:DryMongoBinary generateOptions +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +1ms
  MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '/home/naman114/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'pop',
    codename: 'jammy',
    release: '22.04',
    id_like: [ 'ubuntu', 'debian' ]
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +1ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13',
  modulesCache: '/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/node_modules/.cache/mongodb-memory-server/mongod-x64-pop-5.0.13',
  relative: '/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/mongodb-binaries/mongod-x64-pop-5.0.13',
  resolveConfig: '/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13'
}  +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13" +2ms
  MongoMS:DryMongoBinary locateBinary: running generateDownloadPath +1ms
  MongoMS:DryMongoBinary generateDownloadPath: Generating Download Path, preferGlobal: "true" +0ms
  MongoMS:DryMongoBinary generatePaths {
  version: '5.0.13',
  downloadDir: '/home/naman114/.cache/mongodb-binaries',
  os: {
    os: 'linux',
    dist: 'pop',
    codename: 'jammy',
    release: '22.04',
    id_like: [ 'ubuntu', 'debian' ]
  },
  platform: 'linux',
  arch: 'x64',
  systemBinary: ''
} +0ms
  MongoMS:DryMongoBinary getBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +1ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generatePaths: resolveConfigValue is not empty +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary combineBinaryName +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Paths: {
  legacyHomeCache: '/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13',
  modulesCache: '/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/node_modules/.cache/mongodb-memory-server/mongod-x64-pop-5.0.13',
  relative: '/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/mongodb-binaries/mongod-x64-pop-5.0.13',
  resolveConfig: '/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13'
}  +0ms
  MongoMS:DryMongoBinary generateDownloadPath: Found binary in resolveConfig (DOWNLOAD_DIR): "/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13" +1ms
  MongoMS:DryMongoBinary locateBinary: found binary at "/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13" +1ms
  MongoMS:MongoBinary getPath: Mongod binary path: "/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13" +8ms
  MongoMS:MongoInstance Mongo[42519]: start: Starting Processes +44ms
  MongoMS:MongoInstance Mongo[42519]: _launchMongod: Launching Mongod Process +3ms
  MongoMS:MongoInstance Mongo[42519]: prepareCommandArgs +1ms
  MongoMS:MongoInstance Mongo[42519]: prepareCommandArgs: final argument array:["--port","42519","--dbpath","/tmp/mongo-mem-2dJgBS","--storageEngine","ephemeralForTest","--bind_ip","127.0.0.1","--noauth"] +0ms
  MongoMS:MongoInstance Mongo[42519]: _launchKiller: Launching Killer Process (parent: 25244, child: 25269) +17ms
  MongoMS:MongoInstance Mongo[42519]: stderrHandler: ""/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13)"" +19ms
  MongoMS:MongoInstance Mongo[42519]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code! +8ms
  MongoMS:MongoInstance Mongo[42519]: constructor: Instance has thrown an Error: Error: Instance closed unexpectedly with code "1" and signal "null" +1ms
  MongoMS:MongoInstance Mongo[42519]: stop +0ms
  MongoMS:utils Mongo[42519] killProcess: given childProcess's PID was not alive anymore +75ms
  MongoMS:MongoInstance Mongo[42519]: closeHandler: code: "1", signal: "null" +1ms
  MongoMS:utils Mongo[42519] killProcess: killerProcess: sending "SIGINT" +1ms
  MongoMS:MongoMemoryServer Mongo[unknown]: _startUpInstance threw a Error:  UnexpectedCloseError: Instance closed unexpectedly with code "1" and signal "null"
    at MongoInstance.closeHandler (/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:546:52)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14) +100ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method +26ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?) +0ms
  console.log
    UnexpectedCloseError: Instance closed unexpectedly with code "1" and signal "null"
        at MongoInstance.closeHandler (/home/naman114/Projects/Aumyaa/AumRM-Tool/backend/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:546:52)
        at ChildProcess.emit (node:events:513:28)
        at maybeClose (node:internal/child_process:1093:16)
        at Socket.<anonymous> (node:internal/child_process:451:11)
        at Socket.emit (node:events:513:28)
        at Pipe.<anonymous> (node:net:757:14)

      at Object.log (__tests__/template.test.js:9:13)

  MongoMS:utils Mongo[42519] killProcess: killerProcess: got exit signal, Code: null, Signal: SIGINT +77ms
  MongoMS:MongoInstance Mongo[42519]: stop: Instance Finished Shutdown +79ms
 PASS  __tests__/template.test.js
  Example Test Suite
    ✓ Example (3 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.943 s, estimated 1 s
Ran all test suites.
```

</details>

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2023-03-18 11:58
Duplicate of #732

**Closed by hasezoey** 2023-03-18 11:58 UTC
Labels: bug

**Comment by hasezoey** [comment] 2023-03-18 12:00
>   MongoMS:MongoInstance Mongo[42519]: stderrHandler: ""/home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/naman114/.cache/mongodb-binaries/mongod-x64-pop-5.0.13)"" +19ms

you are running a distro that does not ship openssl 1.1.1, but the selected mongodb version requires it
in case of ubuntu 2204 you will either have to install openssl 1.1 through a ppa for older version, or manually set the version to 6.0.4 or higher, see [config option VERSION](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version)
