### ISSUE TITLE
Fail to install the version 6.7.6

### ISSUE THREAD

**Issue by bpedroso** [nodkz/mongodb-memory-server#380] opened 2020-09-16 23:33 UTC
## Versions

- NodeJS: v14.3.0
- mongodb-memory-server-*: 6.7.6
- mongodb: 0.0.0
- mongoose: 5.7.14
- system: Docker (node:8.12.0-slim)

package: mongo-memory-server 

## What is the Problem?

The problem happens on postinstall process when executing install as a dockerfile step. The 6.7.5 works fine.

```
 RUN npm cache clean --force && rm -rf ~/.npm && npm config set strict-ssl false && rm -rf node_modules/ && rm -f package-lock.json && npm install
```

## Error message

```shell
> mongodb-memory-server@6.7.6 postinstall /Offer/node_modules/mongodb-memory-server
> node ./postinstall.js

[91m/Offer/node_modules/camelcase/index.js:17
		} else if (isLastCharUpper && isLastLastCharUpper && /[\p{Ll}]/u.test(character)) {
		                              ^

SyntaxError: Invalid regular expression: /[\p{Ll}]/: Invalid escape
    at preserveCamelCase (/Offer/node_modules/camelcase/index.js:17:33)
    at Object.camelCase [as default] (/Offer/node_modules/camelcase/index.js:63:11)
    at resolveConfig (/Offer/node_modules/mongodb-memory-server-core/lib/util/resolve-config.js:43:217)
    at Object.<anonymous> (/Offer/node_modules/mongodb-memory-server-core/lib/util/resolve-config.js:56:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2020-09-17 08:07
your docker's nodejs version is 8.12, the required nodejs version is 10.15.0
https://github.com/nodkz/mongodb-memory-server#requirements
https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/package.json#L12-L14

**Comment by LamineMbn** [comment] 2020-09-17 09:40
Minor versions mustn't have breaker changes, the version 6 must still function with Node 8

**Comment by hasezoey** [comment] 2020-09-17 10:36
@LamineMbn i know, but the dependencies were already upgraded, and they needed nodejs 10.15+ and this repo didnt have tests for nodejs below 10 for an long time (that is why the dependency problem wasnt noticed)

**Comment by hasezoey** [comment] 2020-09-29 16:31
Duplicate of #379

**Closed by hasezoey** 2020-09-29 16:31 UTC
Labels: bug
