### ISSUE TITLE
Apple m1 chip support

### ISSUE THREAD

**Issue by IlyaEremin** [nodkz/mongodb-memory-server#429] opened 2021-01-12 16:52 UTC
I 

## Versions

- NodeJS: v14.15.4
- mongodb-memory-server-*: 6.6.1
- mongodb: 3.5.5
- mongoose: 5.7.14
- system: MacOS 11.1

package: mongo-memory-server 

## What is your question?

When I run jest test which is using mongodb-memory-server on apple m1 chip I get: unsupported architecture, ia32 and x64 are the only valid options

So my question: is this about mongodb-memory-server or is it about mongodb itself? I suspect this problem related to mongodb engine, but just to confirm (and for the future googlers).

**Comment by hasezoey** [comment] 2021-01-12 17:13
Duplicate of #422

**Closed by hasezoey** 2021-01-12 17:13 UTC
Labels: question
