### ISSUE TITLE
Not work on Windows 10 Home edition

### ISSUE THREAD

**Issue by Kalter666** [nodkz/mongodb-memory-server#138] opened 2019-02-15 17:40 UTC
Hi,
I'm using jest for testing.
The issue found on laptop that runs win 10 home.
However everything works fine under Manjaro and Bash on Ubuntu on Windows, on Win 10 Pro works great too.
I have tried a different versions of node (11.8 - 11.10, 10.15.1 which is LTS).
Problem is infinite download of MongoDB, in normal case It's downloading while npm install in process.
I have tried setting jest.setTimeout to 10e5 which is pretty much, once download finishes another one starts.

**Comment by nodkz** [comment] 2019-02-15 23:33
Sorry, I don't have windows machine. So i cannot debug your case.

Any help with this issue from community is very appreciative.

**Comment by Kalter666** [comment] 2019-02-16 11:45
I found an interesting thing.
On both Windows machines .cache in node_modules aren't exist!
I think problem may exists in 173 line in this [file](https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownload.js). May be it need a parameter "recursive" set to "true". 
But I don't know how to test it.

**Comment by nodkz** [comment] 2019-03-12 17:00
Just fix compiled files in you `node_modules` and try to run your tests again.

**Comment by Kalter666** [comment] 2019-03-12 17:37
On still no node_modules/.cache/mongodb-memory-server/mongodb-binaries directory.

**Comment by nodkz** [comment] 2019-03-12 17:41
Somebody with Windows environment please help to resolve this issue. I'm on MacOS. 👐

Thanks.

**Comment by martin-watts** [comment] 2019-03-19 13:43
I can confirm the problem is that the node_modules/.cache/ directory is being removed, this is the same problem as #159.

I've worked around it by setting the MONGOMS_DOWNLOAD_DIR environment variable to somewhere that doesn't get cleaned up automatically. 

e.g. (on Windows):

`
set MONGOMS_DOWNLOAD_DIR=%cd%\.mongo-ms
`
Then, if you haven't already run `npm install`
`npm install`

or, if you have:
`node node node_modules\mongodb-memory-server\scripts\postinstall.js`

The mongo binaries get stored in the `.mongo-ms` directory

**To run tests:** 
Ensure the environment variable is set before running any tests:
`
set MONGOMS_DOWNLOAD_DIR=%cd%\.mongo-ms
npm test
`
To ensure the binaries get picked up from the correct directory. 

(Full disclosure: 
I want this to work across OS's, so what I've _actually_ done is used [cross-env](https://www.npmjs.com/package/cross-env), and set the test script in my package.json to: 
`cross-env MONGOMS_DOWNLOAD_DIR=.mongo-ms jest`)

**Comment by hasezoey** [comment] 2019-12-20 09:51
is this still a problem in newer versions?

**Comment by hasezoey** [comment] 2019-12-27 18:33
Closing this because of the similarity of #159

**Closed by hasezoey** 2019-12-27 18:33 UTC
Labels: help wanted
