### ISSUE TITLE
Package doesn't download correct 4.0.x version for win32

### ISSUE THREAD

**Issue by bhsi3h** [nodkz/mongodb-memory-server#399] opened 2020-10-06 23:08 UTC
## Versions

- NodeJS: v10.16.0
- mongodb-memory-server-*: 5.2.11
- mongodb: 3.2.7
- jest: 23.6.0
- system: Windows

package: mongo-memory-server 

## What is the Problem?

The Gitlab CI fails by having creating a new instance of mongodb-memory-server. This is for unit testing, and I have only imported the package into the file. 

Gitlab CI Error Below:
```
  Use debug option for more info: new MongoMemoryServer({ debug: true })
  at /node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:87:17
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    Error: Cannot read property 'toString' of undefined
```

## Code Example

```ts
import { MongoMemoryServer } from 'mongodb-memory-server';

jest.setTimeout(60000);

describe('access', () => {
  let test: MongoMemoryServer;

  beforeAll(async() => {
    test = new MongoMemoryServer();
  });

  it('Should throw error', () => {
    let result = false;
    expect(result).toEqual(false);
  });

  afterAll((done: DoneFn) => {
    test.stop().then((result) => {
      done();
    });
  });
  
});
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2020-10-07 07:59
if possible, please upgrade to `6.9.0` and re-post the error if it still happens

**Comment by bhsi3h** [comment] 2020-10-07 15:27
> if possible, please upgrade to `6.9.0` and re-post the error if it still happens
> 
> and if the error still happens, please also provide the full [debug log](https://github.com/nodkz/mongodb-memory-server#enable-debug-mode)

Package updated to 6.90 and updated mongodb to 3.6.2. and receiving the following error (included debug):

```
NODE_ENV values of test detected. Assuming this is done automatically by Jest. Using empty config object.
2020-10-07T15:19:16.217Z MongoMS:MongoBinary MongoBinary: Download lock removed
2020-10-07T15:19:16.217Z MongoMS:MongoBinary MongoBinary: Mongod binary path: "/builds/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod"
2020-10-07T15:19:16.352Z MongoMS:MongoMemoryServer Called MongoMemoryServer.stop() method
2020-10-07T15:19:16.352Z MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method
2020-10-07T15:19:16.355Z MongoMS:MongoInstance Mongo[40835]: MongodbInstance: Instance has failed: Error: spawn /builds/tmobile/isa/pronghorn/api-epif/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod ENOENT
2020-10-07T15:19:16.371Z MongoMS:MongoInstance Mongo[40835]: Mongod instance closed with an non-0 code!
2020-10-07T15:19:16.371Z MongoMS:MongoInstance Mongo[40835]: CLOSE: -2
2020-10-07T15:19:16.371Z MongoMS:MongoInstance Mongo[40835]: MongodbInstance: Instance has failed: Mongod instance closed with code "-2"

    Error: Spawned Mongo Instance PID is undefined
        at MongoInstance.Object.<anonymous>.MongoInstance._launchMongod (/builds/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:235:13)
```

**Comment by hasezoey** [comment] 2020-10-07 15:35
@bhsi3h the log says it all, the file this package tries to execute dosnt exist, `ENOENT`

you installed package `mongo-memory-server`, correct? if yes, then this package should have downloaded the correct mongod file on package-install (npm install / yarn install) - did you skip it or did it error?

**Comment by bhsi3h** [comment] 2020-10-07 15:41
> @bhsi3h the log says it all, the file this package tries to execute dosnt exist, `ENOENT`
> 
> you installed package `mongo-memory-server`, correct? if yes, then this package should have downloaded the correct mongod file on package-install (npm install / yarn install) to local `node_modules/` - did you skip it or did it error?

Just went through the response when I ran the install command, it did give back the error:
```
failed to download/install MongoDB binaries. The error: Error: Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
  Used Url: "https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-4.0.14.zip"
Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
```
I will try downloading it and reporting back

**Comment by hasezoey** [comment] 2020-10-07 15:44
is your problem maybe related / the same as #55 ? (especially: https://github.com/nodkz/mongodb-memory-server/issues/55#issuecomment-694799998)

**Comment by bhsi3h** [comment] 2020-10-07 16:07
> is your problem maybe related / the same as #55 ? (especially: [#55 (comment)](https://github.com/nodkz/mongodb-memory-server/issues/55#issuecomment-694799998))
> 
> PS: does `http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.0.14.zip` work?
> 
> EDIT: you can overwrite the download link temporary with `MONGOMS_DOWNLOAD_URL=url`

The link works. I did take a look at the cache dir and it seemed like it didn't download everything it needed from the original link.

Pardon me, but how would I run the command to overwrite the download link?

**Comment by hasezoey** [comment] 2020-10-07 16:12
basicly `MONGOMS_DOWNLOAD_URL=url npm i` (or use cross-env (package))

**Comment by hasezoey** [comment] 2020-10-07 16:13
so basicly this is an duplicate of what was said in https://github.com/nodkz/mongodb-memory-server/issues/55#issuecomment-694799998 , right?

(i will leave this open, because #55 is already old and closed)

**Comment by hasezoey** [comment] 2020-10-07 16:19
@bhsi3h @austi10 can you confirm #400 fixes this issue?

**Closed** 2020-10-07 16:42 UTC
Labels: Module: Version-String Generation, bug

**Comment by bhsi3h** [comment] 2020-10-07 17:07
@hasezoey I just reinstalled 6.9.1. I am not getting that 403 error anymore but still receiving ENOENT on Gitlab CI Pipeline. My issue may be pointing something else.

**Comment by hasezoey** [comment] 2020-10-07 17:55
if you dont get an install error anymore, then the pipeline shouldnt fail
-> maybe node_modules caching is enabled and with that no new `npm install` command is run?

**Comment by bhsi3h** [comment] 2020-10-07 18:09
Yeah the Pipeline runs on Linux. It spins up a docker image with Alpine. Maybe Alpine has issue with Mongodb? I will put into new issue if its out of scope.

Debug turned off
```
NODE_ENV values of test detected. Assuming this is done automatically by Jest. Using empty config object.
  console.warn node_modules//dist/config/default.js:7
    NODE_ENV values of test detected. Assuming this is done automatically by Jest. Using empty config object.
  console.warn node_modules/mongodb-memory-server-core/lib/MongoMemoryServer.js:143
    Starting the instance failed, please enable debug for more infomation
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    Error: Spawned Mongo Instance PID is undefined
        at MongoInstance.Object.<anonymous>.MongoInstance._launchMongod (/builds/tmobile/isa/pronghorn/api-epif/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:235:13)
        at MongoInstance.<anonymous> (/builds/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:140:30)
        at step (/builds/mongodb-memory-server-core/lib/util/MongoInstance.js:44:23)
        at Object.next (/builds/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:25:53)
        at fulfilled (/builds/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:16:58)
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    **Error: spawn /builds/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod ENOENT**
        at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
        at onErrorNT (internal/child_process.js:415:16)
        at process._tickCallback (internal/process/next_tick.js:63:19)
FAIL spec/dataAccess.spec.ts (61.278s)
```

**Comment by hasezoey** [comment] 2020-10-07 18:18
@bhsi3h yes, Alpine is the issue, look into https://github.com/nodkz/mongodb-memory-server/issues/347 for more
