### ISSUE TITLE
Error: "instanceInfo" is undefined

### ISSUE THREAD

**Issue by Stono** [nodkz/mongodb-memory-server#501] opened 2021-07-06 09:16 UTC
Hey, 
Just updated to `7.1.0` and our tests started doing this:

```
  1) Mongo Store
       "before each" hook for "should create items":
     Error: "instanceInfo" is undefined
      at assertionInstanceInfo (node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:725:2)
      at MongoMemoryServer.getUri (node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:640:5)
      at Function.FromInMemory (lib/client.ts:75:30)
      at Context.<anonymous> (test/index.test.ts:29:14)
```

Turns out I could resolve the issue by explicitly calling `.start()`, which on `6.x.x` we didn't have to do.

It's no biggie, but a change in behaviour I figure I'd share in case others were left confused by it.  Might be good to perhaps instead error with "Please call .start() before .getUri()"?

**Comment by hasezoey** [comment] 2021-07-06 09:41
Duplicate of #497

**Closed by hasezoey** 2021-07-06 09:41 UTC
Labels: bug

**Comment by Stono** [comment] 2021-07-06 10:04
Sorry for the dupe :)
